name: 'Build Project'
on: [push]

jobs:
  build-silice:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Download Silice
        shell: bash
        run: |
          wget -c https://github.com/sylefeb/silice-for-github/releases/download/bucket-linux-x64/release.tgz
          tar xvfz release.tgz
          mkdir -p /usr/local/share/silice
          mv release/silice /usr/local/share/silice
          mv release/bin/* /usr/bin/
          echo '/usr/local/share/silice/oss-cad-suite/bin/' >>"${GITHUB_PATH}"
          echo '/usr/local/share/silice/oss-cad-suite/lib/' >>"${GITHUB_PATH}"
          echo '/usr/local/share/silice/oss-cad-suite/share/verilator/bin/' >>"${GITHUB_PATH}"
          echo "QT_PLUGIN_PATH=/usr/local/share/silice/oss-cad-suite/lib/qt5/plugins" >> $GITHUB_ENV
          echo "GTK_EXE_PREFIX=/usr/local/share/silice/oss-cad-suite/" >> $GITHUB_ENV
          echo "GTK_DATA_PREFIX=/usr/local/share/silice/oss-cad-suite/" >> $GITHUB_ENV
          echo "GDK_PIXBUF_MODULEDIR=/usr/local/share/silice/oss-cad-suite/lib/gdk-pixbuf-2.0/2.10.0/loaders" >> $GITHUB_ENV
          echo "GDK_PIXBUF_MODULE_FILE=/usr/local/share/silice/oss-cad-suite/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache" >> $GITHUB_ENV
          echo "OPENFPGALOADER_SOJ_DIR=/usr/local/share/silice/oss-cad-suite/share/openFPGALoader" >> $GITHUB_ENV
      - name: Build project
        shell: bash
        run : |
          make project
      - name: Copy bitstream
        run: |
          ./copy_bitstream.sh
      - name: Upload as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: bitstream
          path: bitstream
