name: 'Build Project'
on: [push]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-silice:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Silice
        uses: sylefeb/silice-for-github@v1.1
      - name: Build project
        shell: bash
        run : |
          make project
      - name: Copy bitstream
        run: |
          ./copy_bitstream.sh
      - name: Upload as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: bitstream
          path: bitstream
  tests:
    uses: ./.github/workflows/pages.yaml
    needs: [build-silice]
