name: programming
description: 'Creates a page for programming your FPGA'
on: [workflow_call]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  make-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Download bitstream artifact
        uses: actions/download-artifact@v4
        with:
          name: bitstream
          path: gh-pages

      - name: Generate HTML page
        shell: bash
        run: |
          cat << EOF >> gh-pages/index.html
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <title>FPGA programming page</title>
            </head>
            <body>
            <p>This is a test</p>
            </body>
            </html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'gh-pages'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Check for failure
        if: failure()
        shell: bash
        run: |
          echo "Failed to deploy to GitHub Pages, please follow the link to troubleshoot: https://tinytapeout.com/faq/#my-github-action-is-failing-on-the-pages-part"

          cat << EOF >> $GITHUB_STEP_SUMMARY
          # Error
          Failed to deploy to GitHub Pages. [Click here for instructions how to fix](https://tinytapeout.com/faq/#my-github-action-is-failing-on-the-pages-part).
          EOF

          exit 1

      - name: Link in workflow summary
        shell: bash
        run: |
          PAGE_URL=${{ steps.deployment.outputs.page_url }}
          PAGE_URL=$(echo "$PAGE_URL" | sed -e 's/\/$//')
          cat << EOF >> $GITHUB_STEP_SUMMARY
          # Program you FPGA
          [go to programming page]($PAGE_URL/index.html)
          EOF
